version: '3.7'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data: